### ISSUE TITLE
Suggesting a few additional summer schools

### ISSUE THREAD

**Issue by tmorshed** [FBen3/awesome-BCIss#1]
Hey there! Great resource here - wanted to suggest a couple of other summer schools you can add as well:
- Okinawa Summer School happening every July-ish: https://groups.oist.jp/ocnc
- Allen Institute workshop every August in Seattle: https://alleninstitute.org/events/summer-workshop-on-the-dynamic-brain-2023/
- Woods Hole Summer schools: [Methods in Comp Neurosci](https://www.mbl.edu/education/advanced-research-training-courses/course-offerings/methods-computational-neuroscience) and [Brains, Minds, and Machines](https://cbmm.mit.edu/news-events/events/summer-course-mbl-woods-hole-brains-minds-and-machines). Every July-August. The Former is not fully free but the latter is always fully covered incl. accommodation.
- Krembil Centre for Neuroinformatics (KCNI) summer school in Toronto, every July-ish: https://kcnischool.org. This is free to register and attend but does not cover accommodation. More geared towards in-province attendees. in Toronto, Ontario, Canada. [shameless plug :)]

**Comment by FBen3** [comment]
@tmorshed Thank you for these awesome suggestions! Especially the one in Toronto - I'm actually from there myself so it's amazing to see the community grow back home.

I've raised a PR (still in Draft), and I'll merge once I've added all the ones from your list.

Thanks again for being the **first** contributor! 🏆🧠
